name: Start
on:
    workflow_dispatch:
      inputs:
        chosen-os:
          required: true
          type: choice
          options:
          - Ubuntu
          - macOS 
jobs:
    test:
      runs-on: ["${{ inputs.chosen-os }}-latest"]
      steps:
      - run: echo Hello world!